version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Ascmh2025_
    ports:
      - "1433:1433"
    networks:
      - pjnet
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Ascmh2025_ -Q 'SELECT 1' -No -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pj_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__HEContext=Server=sqlserver;Database=ExpenseControl;User Id=sa;Password=Ascmh2025_;TrustServerCertificate=True;
    ports:
      - "5001:5092"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - pjnet
 
networks:
  pjnet:
    driver: bridge