name: CI .NET

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Instalar .NET SDK LTS
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Altere para a versão LTS usada no projeto

      - name: Restaurar dependências
        run: dotnet restore PJ_API.csproj

      - name: Compilar projeto
        run: dotnet build PJ_API.csproj --no-restore --configuration Release

