name: CI .NET

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Instalar .NET SDK LTS
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Altere para a versão LTS usada no projeto

      - name: Restaurar dependências
        run: dotnet restore PJ_API.csproj

      - name: Compilar projeto
        run: dotnet build PJ_API.csproj --no-restore --configuration Release

# Job para merge automático na main após PR ser concluído
merge-to-main:
  if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
  runs-on: ubuntu-latest
  needs: build-and-test
  steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        token: ${{ plIQtifP1k8NXqrb0uLn3tqm6oIvkMt4ImGyVzPE5ASUaQq78l1gZN29nK240HWI}}
    - name: Merge PR na main
      uses: peter-evans/merge@v4
      with:
        merge_method: merge
        commit_message: 'Merge automático após aprovação do PR'
        pull_request: ${{ github.event.pull_request.number }}

